from __future__ import annotations

from typing import Any

import pyarrow as pa

SCHEMA_MAJOR = 2
SCHEMA_MINOR = 0
UTC_TIMESTAMP = pa.timestamp("us", tz="UTC")

COMMON_FIELDS: tuple[Any, ...] = (
    pa.field("schema_version", pa.int32(), nullable=False),
    pa.field("evidence_generation_id", pa.string(), nullable=False),
    pa.field("published_at", UTC_TIMESTAMP, nullable=False),
    pa.field("extractor_name", pa.string(), nullable=False),
    pa.field("extractor_version", pa.string(), nullable=False),
)


def _schema(table: str, fields: tuple[Any, ...]) -> pa.Schema:
    return pa.schema(
        (*COMMON_FIELDS, *fields),
        metadata={
            b"flameox.table": table.encode(),
            b"flameox.schema.major": str(SCHEMA_MAJOR).encode(),
            b"flameox.schema.minor": str(SCHEMA_MINOR).encode(),
        },
    )


SCHEMAS: dict[str, pa.Schema] = {
    "runs": _schema(
        "runs",
        (
            pa.field("run_id", pa.string(), nullable=False),
            pa.field("run_revision", pa.uint64()),
            pa.field("run_manifest_digest", pa.string()),
            pa.field("created_at", UTC_TIMESTAMP, nullable=False),
            pa.field("run_type", pa.string(), nullable=False),
            pa.field("execution_status", pa.string(), nullable=False),
            pa.field("capture_status", pa.string(), nullable=False),
            pa.field("validation_status", pa.string(), nullable=False),
            pa.field("workload_definition_id", pa.string()),
            pa.field("workload_instance_id", pa.string()),
            pa.field("measurement_protocol_id", pa.string()),
            pa.field("source_measurement_run_id", pa.string()),
            pa.field("environment_id", pa.string(), nullable=False),
            pa.field("source_state_id", pa.string()),
            pa.field("adapter", pa.string()),
            pa.field("adapter_version", pa.string()),
            pa.field("run_semantic_id", pa.string(), nullable=False),
            pa.field("exit_code", pa.int32()),
            pa.field("wall_time_ns", pa.int64()),
            pa.field("orchestrator", pa.string()),
            pa.field("provider", pa.string()),
            pa.field("lease_id", pa.string()),
            pa.field("worker_id", pa.string()),
            pa.field("orchestration_run_id", pa.string()),
            pa.field("execution_identity_id", pa.string()),
            pa.field("execution_identity_quality", pa.string()),
            pa.field("execution_identity_json", pa.string()),
            pa.field("inference_protocol_identity_id", pa.string()),
            pa.field("inference_protocol_identity_json", pa.string()),
            pa.field("limitations", pa.list_(pa.string())),
            pa.field("limitation_details_json", pa.string()),
            pa.field("resource_availability", pa.string()),
            pa.field("manifest_path", pa.string(), nullable=False),
            pa.field("manifest_json", pa.string()),
        ),
    ),
    "runtime_resource_summaries": _schema(
        "runtime_resource_summaries",
        (
            pa.field("run_id", pa.string(), nullable=False),
            pa.field("sampling_interval_ms", pa.int32(), nullable=False),
            pa.field("minimum_free_bytes", pa.uint64()),
            pa.field("staging_growth_bytes", pa.uint64()),
            pa.field("peak_rss_bytes", pa.uint64()),
            pa.field("peak_rss_backend", pa.string()),
            pa.field("policy_termination", pa.string()),
            pa.field("unavailable_metrics", pa.list_(pa.string()), nullable=False),
        ),
    ),
    "runtime_writable_root_growth": _schema(
        "runtime_writable_root_growth",
        (
            pa.field("run_id", pa.string(), nullable=False),
            pa.field("writable_root_identity", pa.string(), nullable=False),
            pa.field("target_path", pa.string(), nullable=False),
            pa.field("growth_bytes", pa.uint64()),
            pa.field("available", pa.bool_(), nullable=False),
            pa.field("unavailable_reason", pa.string()),
        ),
    ),
    "artifact_registrations": _schema(
        "artifact_registrations",
        (
            pa.field("registration_id", pa.string(), nullable=False),
            pa.field("run_id", pa.string(), nullable=False),
            pa.field("artifact_id", pa.string(), nullable=False),
            pa.field("display_name", pa.string(), nullable=False),
            pa.field("kind", pa.string(), nullable=False),
            pa.field("media_type", pa.string(), nullable=False),
            pa.field("byte_length", pa.uint64(), nullable=False),
            pa.field("sensitivity", pa.string(), nullable=False),
            pa.field("role", pa.string(), nullable=False),
            pa.field("producer", pa.string()),
            pa.field("producer_version", pa.string()),
            pa.field("registered_at", UTC_TIMESTAMP, nullable=False),
        ),
    ),
    "adapter_extractions": _schema(
        "adapter_extractions",
        (
            pa.field("extraction_id", pa.string(), nullable=False),
            pa.field("run_id", pa.string(), nullable=False),
            pa.field("input_artifact_id", pa.string(), nullable=False),
            pa.field("adapter", pa.string(), nullable=False),
            pa.field("adapter_package_identity", pa.string(), nullable=False),
            pa.field("extractor_version", pa.string(), nullable=False),
            pa.field("summary_json", pa.string(), nullable=False),
            pa.field("limitations", pa.list_(pa.string()), nullable=False),
        ),
    ),
    "adapter_validations": _schema(
        "adapter_validations",
        (
            pa.field("validation_id", pa.string(), nullable=False),
            pa.field("run_id", pa.string(), nullable=False),
            pa.field("input_artifact_id", pa.string(), nullable=False),
            pa.field("input_byte_length", pa.uint64(), nullable=False),
            pa.field("adapter", pa.string(), nullable=False),
            pa.field("adapter_package_identity", pa.string(), nullable=False),
            pa.field("validator_version", pa.string(), nullable=False),
            pa.field("valid", pa.bool_(), nullable=False),
            pa.field("limitations", pa.list_(pa.string()), nullable=False),
        ),
    ),
    "artifact_pipelines": _schema(
        "artifact_pipelines",
        (
            pa.field("pipeline_id", pa.string(), nullable=False),
            pa.field("run_id", pa.string(), nullable=False),
            pa.field("pipeline_name", pa.string(), nullable=False),
            pa.field("pipeline_schema", pa.string(), nullable=False),
            pa.field("producer", pa.string(), nullable=False),
            pa.field("producer_version", pa.string(), nullable=False),
            pa.field("identity_quality", pa.string(), nullable=False),
            pa.field("workload_identity", pa.string()),
            pa.field("device_identity", pa.string()),
            pa.field("workload_definition_id", pa.string()),
            pa.field("workload_instance_id", pa.string()),
            pa.field("command_digest", pa.string()),
            pa.field("parameters_digest", pa.string()),
            pa.field("compiler_identity_id", pa.string()),
            pa.field("build_protocol_id", pa.string()),
            pa.field("target_identity_id", pa.string()),
            pa.field("source_state_id", pa.string()),
            pa.field("environment_id", pa.string(), nullable=False),
            pa.field("stages_json", pa.string(), nullable=False),
            pa.field("limitations", pa.list_(pa.string()), nullable=False),
            pa.field("created_at", UTC_TIMESTAMP, nullable=False),
        ),
    ),
    "kernel_validation_cases": _schema(
        "kernel_validation_cases",
        (
            pa.field("case_output_id", pa.string(), nullable=False),
            pa.field("run_id", pa.string(), nullable=False),
            pa.field("artifact_id", pa.string(), nullable=False),
            pa.field("case_id", pa.string(), nullable=False),
            pa.field("output_name", pa.string(), nullable=False),
            pa.field("case_status", pa.string(), nullable=False),
            pa.field("output_status", pa.string(), nullable=False),
            pa.field("coverage_complete", pa.bool_(), nullable=False),
            pa.field("producer", pa.string(), nullable=False),
            pa.field("producer_version", pa.string()),
            pa.field("reference_name", pa.string(), nullable=False),
            pa.field("reference_version", pa.string()),
            pa.field("reference_identity", pa.string(), nullable=False),
            pa.field("device", pa.string(), nullable=False),
            pa.field("seed", pa.int64()),
            pa.field("dimensions_json", pa.string(), nullable=False),
            pa.field("inputs_json", pa.string(), nullable=False),
            pa.field("dtype", pa.string(), nullable=False),
            pa.field("shape", pa.list_(pa.int64()), nullable=False),
            pa.field("representative_failures_json", pa.string(), nullable=False),
            pa.field("limitations", pa.list_(pa.string()), nullable=False),
        ),
    ),
    "kernel_validation_metrics": _schema(
        "kernel_validation_metrics",
        (
            pa.field("metric_id", pa.string(), nullable=False),
            pa.field("case_output_id", pa.string(), nullable=False),
            pa.field("run_id", pa.string(), nullable=False),
            pa.field("artifact_id", pa.string(), nullable=False),
            pa.field("case_id", pa.string(), nullable=False),
            pa.field("output_name", pa.string(), nullable=False),
            pa.field("metric_name", pa.string(), nullable=False),
            pa.field("value", pa.float64()),
            pa.field("value_kind", pa.string()),
            pa.field("positive_infinity_reason", pa.string()),
            pa.field("comparator", pa.string()),
            pa.field("threshold", pa.float64()),
            pa.field("unit", pa.string(), nullable=False),
            pa.field("metric_profile_json", pa.string()),
            pa.field("metric_identity_id", pa.string()),
            pa.field("status", pa.string(), nullable=False),
            pa.field("limitation", pa.string()),
        ),
    ),
    "kernel_validation_comparisons": _schema(
        "kernel_validation_comparisons",
        (
            pa.field("comparison_id", pa.string(), nullable=False),
            pa.field("baseline_run_set_id", pa.string(), nullable=False),
            pa.field("candidate_run_set_id", pa.string(), nullable=False),
            pa.field("experiment_id", pa.string()),
            pa.field("protocol_identity_id", pa.string()),
            pa.field("metric", pa.string()),
            pa.field("unit", pa.string()),
            pa.field("metric_source", pa.string(), nullable=False),
            pa.field("polarity", pa.string()),
            pa.field("estimand", pa.string()),
            pa.field("practical_threshold", pa.float64()),
            pa.field("estimate", pa.float64()),
            pa.field("confidence_low", pa.float64()),
            pa.field("confidence_high", pa.float64()),
            pa.field("confidence_level", pa.float64()),
            pa.field("method", pa.string(), nullable=False),
            pa.field("independent_unit", pa.string(), nullable=False),
            pa.field("complete_pair_n", pa.uint64(), nullable=False),
            pa.field("decision", pa.string(), nullable=False),
            pa.field("validity", pa.string(), nullable=False),
            pa.field("pair_count", pa.uint64(), nullable=False),
            pa.field("aggregate_count", pa.uint64(), nullable=False),
            pa.field("compatibility_mismatch_count", pa.uint64(), nullable=False),
            pa.field("baseline_only_count", pa.uint64(), nullable=False),
            pa.field("candidate_only_count", pa.uint64(), nullable=False),
            pa.field("mismatches", pa.list_(pa.string()), nullable=False),
            pa.field("input_artifact_ids", pa.list_(pa.string()), nullable=False),
            pa.field("result_digest", pa.string(), nullable=False),
        ),
    ),
    "kernel_validation_comparison_pairs": _schema(
        "kernel_validation_comparison_pairs",
        (
            pa.field("comparison_id", pa.string(), nullable=False),
            pa.field("pair_id", pa.string(), nullable=False),
            pa.field("semantic_identity_id", pa.string(), nullable=False),
            pa.field("semantic_identity_json", pa.string(), nullable=False),
            pa.field("independent_unit_id", pa.string(), nullable=False),
            pa.field("baseline_run_id", pa.string(), nullable=False),
            pa.field("candidate_run_id", pa.string(), nullable=False),
            pa.field("baseline_artifact_id", pa.string(), nullable=False),
            pa.field("candidate_artifact_id", pa.string(), nullable=False),
            pa.field("case_id", pa.string(), nullable=False),
            pa.field("output_name", pa.string(), nullable=False),
            pa.field("metric_name", pa.string(), nullable=False),
            pa.field("unit", pa.string(), nullable=False),
            pa.field("comparator", pa.string(), nullable=False),
            pa.field("threshold", pa.float64()),
            pa.field("polarity", pa.string(), nullable=False),
            pa.field("baseline_value_json", pa.string(), nullable=False),
            pa.field("candidate_value_json", pa.string(), nullable=False),
            pa.field("baseline_status", pa.string(), nullable=False),
            pa.field("candidate_status", pa.string(), nullable=False),
            pa.field("status_transition", pa.string(), nullable=False),
            pa.field("change_kind", pa.string(), nullable=False),
            pa.field("signed_change", pa.float64()),
            pa.field("absolute_change", pa.float64()),
            pa.field("relative_change_percent", pa.float64()),
            pa.field("relative_change_unavailable_reason", pa.string()),
            pa.field("direction", pa.string(), nullable=False),
        ),
    ),
    "kernel_validation_comparison_aggregates": _schema(
        "kernel_validation_comparison_aggregates",
        (
            pa.field("comparison_id", pa.string(), nullable=False),
            pa.field("semantic_identity_id", pa.string(), nullable=False),
            pa.field("metric_name", pa.string(), nullable=False),
            pa.field("unit", pa.string(), nullable=False),
            pa.field("polarity", pa.string(), nullable=False),
            pa.field("pair_count", pa.uint64(), nullable=False),
            pa.field("finite_pair_count", pa.uint64(), nullable=False),
            pa.field("positive_infinity_pair_count", pa.uint64(), nullable=False),
            pa.field("median_signed_change", pa.float64()),
            pa.field("direction", pa.string(), nullable=False),
        ),
    ),
    "kernel_validation_comparison_gaps": _schema(
        "kernel_validation_comparison_gaps",
        (
            pa.field("gap_id", pa.string(), nullable=False),
            pa.field("comparison_id", pa.string(), nullable=False),
            pa.field("gap_kind", pa.string(), nullable=False),
            pa.field("independent_unit_id", pa.string(), nullable=False),
            pa.field("case_id", pa.string(), nullable=False),
            pa.field("output_name", pa.string(), nullable=False),
            pa.field("metric_name", pa.string(), nullable=False),
            pa.field("detail_json", pa.string(), nullable=False),
        ),
    ),
    "pipeline_comparisons": _schema(
        "pipeline_comparisons",
        (
            pa.field("comparison_id", pa.string(), nullable=False),
            pa.field("baseline_pipeline_id", pa.string(), nullable=False),
            pa.field("candidate_pipeline_id", pa.string(), nullable=False),
            pa.field("compatibility", pa.string(), nullable=False),
            pa.field("identity_mismatches", pa.list_(pa.string()), nullable=False),
            pa.field("stages_json", pa.string(), nullable=False),
            pa.field("first_observed_divergent_stage", pa.string()),
            pa.field("input_artifact_ids", pa.list_(pa.string()), nullable=False),
            pa.field("extractor_identities", pa.list_(pa.string()), nullable=False),
            pa.field("limitations", pa.list_(pa.string()), nullable=False),
            pa.field("result_digest", pa.string(), nullable=False),
        ),
    ),
    "reduction_results": _schema(
        "reduction_results",
        (
            pa.field("reduction_id", pa.string(), nullable=False),
            pa.field("plan_id", pa.string(), nullable=False),
            pa.field("disposition", pa.string(), nullable=False),
            pa.field("original_artifact_id", pa.string(), nullable=False),
            pa.field("final_artifact_id", pa.string()),
            pa.field("predicate_definition_id", pa.string(), nullable=False),
            pa.field("predicate_instance_id", pa.string(), nullable=False),
            pa.field("attempts_json", pa.string(), nullable=False),
            pa.field("attempt_receipts_artifact_id", pa.string()),
            pa.field("shrinkray_history_artifact_id", pa.string()),
            pa.field("reducer_stdout_artifact_id", pa.string()),
            pa.field("reducer_stderr_artifact_id", pa.string()),
            pa.field("final_predicate_stdout_artifact_id", pa.string()),
            pa.field("final_predicate_stderr_artifact_id", pa.string()),
            pa.field("cleanup_complete", pa.bool_(), nullable=False),
            pa.field("limitations", pa.list_(pa.string()), nullable=False),
            pa.field("finished_at", UTC_TIMESTAMP, nullable=False),
            pa.field("engine", pa.string()),
            pa.field("input_format", pa.string()),
            pa.field("provider_environment_id", pa.string()),
            pa.field("provider_python_digest", pa.string()),
            pa.field("shrinkray_version", pa.string()),
            pa.field("shrinkray_profile", pa.string()),
            pa.field("shrinkray_executable_digest", pa.string()),
            pa.field("predicate_bridge_digest", pa.string()),
            pa.field("original_size_bytes", pa.uint64()),
            pa.field("final_size_bytes", pa.uint64()),
            pa.field("minimality", pa.string()),
            pa.field("best_known_artifact_id", pa.string()),
            pa.field("final_revalidation_status", pa.string()),
            pa.field("predicate_repetitions", pa.uint64()),
            pa.field("predicate_collapse_rule", pa.string()),
            pa.field("repeatability_status", pa.string()),
            pa.field("budget_exhausted", pa.bool_()),
            pa.field("staging_byte_limit", pa.uint64()),
            pa.field("retained_candidate_byte_limit", pa.uint64()),
        ),
    ),
    "reduction_attempts": _schema(
        "reduction_attempts",
        (
            pa.field("reduction_id", pa.string(), nullable=False),
            pa.field("attempt_id", pa.string(), nullable=False),
            pa.field("candidate_sha256", pa.string(), nullable=False),
            pa.field("candidate_size_bytes", pa.uint64(), nullable=False),
            pa.field("observations_json", pa.string(), nullable=False),
            pa.field("classification", pa.string(), nullable=False),
            pa.field("recorded_at", pa.string(), nullable=False),
        ),
    ),
    "environments": _schema(
        "environments",
        (
            pa.field("environment_id", pa.string(), nullable=False),
            pa.field("observed_at", UTC_TIMESTAMP, nullable=False),
            pa.field("identity_quality", pa.string(), nullable=False),
            pa.field("fields_json", pa.string(), nullable=False),
            pa.field("missing_fields", pa.list_(pa.string()), nullable=False),
        ),
    ),
    "source_states": _schema(
        "source_states",
        (
            pa.field("source_state_id", pa.string(), nullable=False),
            pa.field("identity_quality", pa.string(), nullable=False),
            pa.field("repository_root", pa.string()),
            pa.field("head_commit", pa.string()),
            pa.field("diff_digest", pa.string()),
            pa.field("executable_digest", pa.string()),
            pa.field("build_id", pa.string()),
            pa.field("fields_json", pa.string(), nullable=False),
            pa.field("missing_fields", pa.list_(pa.string()), nullable=False),
        ),
    ),
    "investigations": _schema(
        "investigations",
        (
            pa.field("investigation_id", pa.string(), nullable=False),
            pa.field("question", pa.string(), nullable=False),
            pa.field("symptom", pa.string()),
            pa.field("project_root", pa.string(), nullable=False),
            pa.field("status", pa.string(), nullable=False),
            pa.field("parent_investigation_id", pa.string()),
            pa.field("created_at", UTC_TIMESTAMP, nullable=False),
        ),
    ),
    "hypotheses": _schema(
        "hypotheses",
        (
            pa.field("hypothesis_id", pa.string(), nullable=False),
            pa.field("investigation_id", pa.string(), nullable=False),
            pa.field("revision", pa.int32(), nullable=False),
            pa.field("claim", pa.string(), nullable=False),
            pa.field("prediction", pa.string(), nullable=False),
            pa.field("discriminating_condition", pa.string(), nullable=False),
            pa.field("assessment", pa.string(), nullable=False),
            pa.field("lifecycle", pa.string(), nullable=False),
            pa.field("created_at", UTC_TIMESTAMP, nullable=False),
        ),
    ),
    "experiments": _schema(
        "experiments",
        (
            pa.field("experiment_id", pa.string(), nullable=False),
            pa.field("investigation_id", pa.string(), nullable=False),
            pa.field("hypothesis_id", pa.string()),
            pa.field("recipe", pa.string(), nullable=False),
            pa.field("recipe_version", pa.string(), nullable=False),
            pa.field("workload_definition_id", pa.string(), nullable=False),
            pa.field("experiment_design_id", pa.string(), nullable=False),
            pa.field("measurement_protocol_id", pa.string(), nullable=False),
            pa.field("validation_spec_id", pa.string()),
            pa.field("primary_metric", pa.string(), nullable=False),
            pa.field("metric_source", pa.string()),
            pa.field("primary_metric_unit", pa.string()),
            pa.field("measurement_series_json", pa.string()),
            pa.field("value_domain", pa.string()),
            pa.field("zero_policy", pa.string()),
            pa.field("polarity", pa.string(), nullable=False),
            pa.field("estimand", pa.string(), nullable=False),
            pa.field("practical_threshold", pa.float64(), nullable=False),
            pa.field("confidence_level", pa.float64(), nullable=False),
            pa.field("stopping_rule_json", pa.string(), nullable=False),
            pa.field("random_seed", pa.uint64(), nullable=False),
            pa.field("role", pa.string(), nullable=False),
            pa.field("created_at", UTC_TIMESTAMP, nullable=False),
        ),
    ),
    "experiment_outcomes": _schema(
        "experiment_outcomes",
        (
            pa.field("experiment_id", pa.string(), nullable=False),
            pa.field("method", pa.string(), nullable=False),
            pa.field("goal", pa.string(), nullable=False),
            pa.field("disposition", pa.string(), nullable=False),
            pa.field("counts_json", pa.string(), nullable=False),
            pa.field("complete_pairs", pa.int32(), nullable=False),
            pa.field("unmatched_cells", pa.int32(), nullable=False),
            pa.field("first_failure_trial_id", pa.string()),
            pa.field("first_failure_factors_json", pa.string()),
            pa.field("limitations", pa.list_(pa.string()), nullable=False),
        ),
    ),
    "variants": _schema(
        "variants",
        (
            pa.field("variant_id", pa.string(), nullable=False),
            pa.field("experiment_id", pa.string(), nullable=False),
            pa.field("name", pa.string(), nullable=False),
            pa.field("treatment_factor", pa.string()),
            pa.field("treatment_value_json", pa.string()),
            pa.field("treatment_identity_id", pa.string()),
            pa.field("identity_quality", pa.string(), nullable=False),
            pa.field("source_state_id", pa.string()),
            pa.field("workload_instance_id", pa.string()),
            pa.field("environment_id", pa.string()),
            pa.field("source_state_ids", pa.list_(pa.string()), nullable=False),
            pa.field("workload_instance_ids", pa.list_(pa.string()), nullable=False),
            pa.field("environment_ids", pa.list_(pa.string()), nullable=False),
            pa.field("combination_ids", pa.list_(pa.string()), nullable=False),
            pa.field("environment_requirements_json", pa.string(), nullable=False),
            pa.field("parameters_json", pa.string(), nullable=False),
            pa.field("varying_factors_json", pa.string(), nullable=False),
            pa.field("limitations", pa.list_(pa.string()), nullable=False),
        ),
    ),
    "trials": _schema(
        "trials",
        (
            pa.field("trial_id", pa.string(), nullable=False),
            pa.field("experiment_id", pa.string(), nullable=False),
            pa.field("variant_id", pa.string(), nullable=False),
            pa.field("run_id", pa.string()),
            pa.field("combination_id", pa.string(), nullable=False),
            pa.field("factors_json", pa.string(), nullable=False),
            pa.field("block_id", pa.string()),
            pa.field("order_in_block", pa.int32()),
            pa.field("parameter_name", pa.string()),
            pa.field("parameter_value_int", pa.int64()),
            pa.field("parameter_value_float", pa.float64()),
            pa.field("attempt", pa.int32(), nullable=False),
            pa.field("outcome", pa.string(), nullable=False),
            pa.field("exclusion_reason", pa.string()),
            pa.field("validation_status", pa.string(), nullable=False),
            pa.field("failure_class", pa.string(), nullable=False),
            pa.field("oracle_receipt_json", pa.string()),
            pa.field("oracle_receipt_artifact_id", pa.string()),
        ),
    ),
    "run_sets": _schema(
        "run_sets",
        (
            pa.field("run_set_id", pa.string(), nullable=False),
            pa.field("corpus_commit_id", pa.string(), nullable=False),
            pa.field("created_at", UTC_TIMESTAMP, nullable=False),
            pa.field("selection_json", pa.string(), nullable=False),
            pa.field("members_json", pa.string(), nullable=False),
            pa.field("membership_digest", pa.string(), nullable=False),
        ),
    ),
    "measurements": _schema(
        "measurements",
        (
            pa.field("measurement_id", pa.string(), nullable=False),
            pa.field("run_id", pa.string(), nullable=False),
            pa.field("artifact_id", pa.string()),
            pa.field("name", pa.string(), nullable=False),
            pa.field("value_int", pa.int64()),
            pa.field("value_float", pa.float64()),
            pa.field("value_uint", pa.uint64()),
            pa.field("value_kind", pa.string()),
            pa.field("unit", pa.string(), nullable=False),
            pa.field("aggregation", pa.string(), nullable=False),
            pa.field("scope", pa.string(), nullable=False),
            pa.field("trial_id", pa.string()),
            pa.field("worker_id", pa.string()),
            pa.field("worker_run_index", pa.int32()),
            pa.field("value_index", pa.int32()),
            pa.field("loop_count", pa.uint64()),
            pa.field("is_warmup", pa.bool_(), nullable=False),
            pa.field("block_id", pa.string()),
            pa.field("variant_id", pa.string()),
            pa.field("order_in_block", pa.int32()),
            pa.field("phase", pa.string()),
            pa.field("dimensions", pa.map_(pa.string(), pa.string())),
            pa.field("evidence_level", pa.string(), nullable=False),
        ),
    ),
    "inference_requests": _schema(
        "inference_requests",
        (
            pa.field("request_id", pa.string(), nullable=False),
            pa.field("run_id", pa.string(), nullable=False),
            pa.field("artifact_id", pa.string(), nullable=False),
            pa.field("source_request_id", pa.string(), nullable=False),
            pa.field("provider_request_id", pa.string()),
            pa.field("input_tokens", pa.int64(), nullable=False),
            pa.field("output_tokens", pa.int64(), nullable=False),
            pa.field("scheduled_ns", pa.int64()),
            pa.field("observed_started_ns", pa.int64()),
            pa.field("ttft_ns", pa.int64()),
            pa.field("latency_ns", pa.int64()),
            pa.field("tpot_ns", pa.int64()),
            pa.field("mean_itl_ns", pa.int64()),
            pa.field("success", pa.bool_()),
            pa.field("cancelled", pa.bool_()),
            pa.field("error_type", pa.string()),
            pa.field("error_code", pa.string()),
            pa.field("queue_ns", pa.int64()),
            pa.field("prefill_ns", pa.int64()),
            pa.field("decode_ns", pa.int64()),
            pa.field("cache_hit", pa.bool_()),
            pa.field("prefix_hash_count", pa.int32()),
            pa.field("evidence_level", pa.string(), nullable=False),
        ),
    ),
    "frames": _schema(
        "frames",
        (
            pa.field("frame_id", pa.string(), nullable=False),
            pa.field("language", pa.string()),
            pa.field("function", pa.string()),
            pa.field("module", pa.string()),
            pa.field("file", pa.string()),
            pa.field("line", pa.int32()),
            pa.field("column", pa.int32()),
            pa.field("address", pa.uint64()),
            pa.field("build_id", pa.string()),
            pa.field("module_relative_address", pa.uint64()),
            pa.field("inline_chain_id", pa.string()),
            pa.field("source_state_id", pa.string()),
            pa.field("artifact_id", pa.string()),
            pa.field("inlined", pa.bool_()),
            pa.field("symbolization", pa.string(), nullable=False),
        ),
    ),
    "frame_measurements": _schema(
        "frame_measurements",
        (
            pa.field("run_id", pa.string(), nullable=False),
            pa.field("artifact_id", pa.string(), nullable=False),
            pa.field("frame_id", pa.string(), nullable=False),
            pa.field("metric", pa.string(), nullable=False),
            pa.field("self_value", pa.int64()),
            pa.field("inclusive_value", pa.int64()),
            pa.field("unit", pa.string(), nullable=False),
            pa.field("sample_count", pa.uint64()),
            pa.field("thread_name", pa.string()),
            pa.field("process_name", pa.string()),
            pa.field("phase", pa.string()),
        ),
    ),
    "call_edges": _schema(
        "call_edges",
        (
            pa.field("run_id", pa.string(), nullable=False),
            pa.field("artifact_id", pa.string(), nullable=False),
            pa.field("parent_frame_id", pa.string(), nullable=False),
            pa.field("child_frame_id", pa.string(), nullable=False),
            pa.field("sample_count", pa.uint64(), nullable=False),
            pa.field("duration_ns", pa.int64(), nullable=False),
        ),
    ),
    "stacks": _schema(
        "stacks",
        (
            pa.field("stack_id", pa.string(), nullable=False),
            pa.field("run_id", pa.string(), nullable=False),
            pa.field("artifact_id", pa.string(), nullable=False),
            pa.field("frame_ids", pa.list_(pa.string()), nullable=False),
            pa.field("leaf_frame_id", pa.string(), nullable=False),
            pa.field("start_ns", pa.int64(), nullable=False),
            pa.field("duration_ns", pa.int64(), nullable=False),
            pa.field("track_id", pa.uint64(), nullable=False),
        ),
    ),
    "observations": _schema(
        "observations",
        (
            pa.field("observation_id", pa.string(), nullable=False),
            pa.field("run_id", pa.string(), nullable=False),
            pa.field("artifact_id", pa.string()),
            pa.field("kind", pa.string(), nullable=False),
            pa.field("name", pa.string(), nullable=False),
            pa.field("value_json", pa.string(), nullable=False),
            pa.field("file", pa.string()),
            pa.field("line_from", pa.int32()),
            pa.field("line_to", pa.int32()),
            pa.field("context", pa.string()),
            pa.field("evidence_level", pa.string(), nullable=False),
        ),
    ),
    "analyses": _schema(
        "analyses",
        (
            pa.field("analysis_id", pa.string(), nullable=False),
            pa.field("recipe", pa.string(), nullable=False),
            pa.field("recipe_version", pa.string(), nullable=False),
            pa.field("parameters_json", pa.string(), nullable=False),
            pa.field("parameters_digest", pa.string(), nullable=False),
            pa.field("corpus_commit_id", pa.string(), nullable=False),
            pa.field("input_generation_ids", pa.list_(pa.string()), nullable=False),
            pa.field("input_run_ids", pa.list_(pa.string()), nullable=False),
            pa.field("input_artifact_ids", pa.list_(pa.string()), nullable=False),
            pa.field("result_digest", pa.string(), nullable=False),
            pa.field("result_artifact_id", pa.string()),
            pa.field("coverage_json", pa.string(), nullable=False),
            pa.field("limitations", pa.list_(pa.string()), nullable=False),
            pa.field("started_at", UTC_TIMESTAMP, nullable=False),
            pa.field("completed_at", UTC_TIMESTAMP, nullable=False),
        ),
    ),
    "evidence_refs": _schema(
        "evidence_refs",
        (
            pa.field("owner_type", pa.string(), nullable=False),
            pa.field("owner_id", pa.string(), nullable=False),
            pa.field("owner_revision", pa.int32()),
            pa.field("ref_type", pa.string(), nullable=False),
            pa.field("ref_id", pa.string(), nullable=False),
            pa.field("relation", pa.string(), nullable=False),
        ),
    ),
    "comparisons": _schema(
        "comparisons",
        (
            pa.field("comparison_id", pa.string(), nullable=False),
            pa.field("experiment_id", pa.string()),
            pa.field("baseline_run_set_id", pa.string(), nullable=False),
            pa.field("candidate_run_set_id", pa.string(), nullable=False),
            pa.field("metric", pa.string(), nullable=False),
            pa.field("unit", pa.string(), nullable=False),
            pa.field("metric_source", pa.string(), nullable=False),
            pa.field("metric_contract_id", pa.string(), nullable=False),
            pa.field("measurement_series_id", pa.string()),
            pa.field("protocol_identity_id", pa.string()),
            pa.field("value_domain", pa.string(), nullable=False),
            pa.field("zero_policy", pa.string(), nullable=False),
            pa.field("polarity", pa.string(), nullable=False),
            pa.field("estimand", pa.string(), nullable=False),
            pa.field("practical_threshold", pa.float64(), nullable=False),
            pa.field("baseline_value_int", pa.int64()),
            pa.field("baseline_value_float", pa.float64()),
            pa.field("candidate_value_int", pa.int64()),
            pa.field("candidate_value_float", pa.float64()),
            pa.field("absolute_change_int", pa.int64()),
            pa.field("absolute_change_float", pa.float64()),
            pa.field("relative_change", pa.float64()),
            pa.field("effect_size", pa.float64()),
            pa.field("confidence_low", pa.float64()),
            pa.field("confidence_high", pa.float64()),
            pa.field("confidence_level", pa.float64()),
            pa.field("method", pa.string(), nullable=False),
            pa.field("random_seed", pa.uint64()),
            pa.field("independent_unit", pa.string(), nullable=False),
            pa.field("paired", pa.bool_(), nullable=False),
            pa.field("baseline_attempted_n", pa.uint64(), nullable=False),
            pa.field("baseline_eligible_n", pa.uint64(), nullable=False),
            pa.field("baseline_failed_n", pa.uint64(), nullable=False),
            pa.field("baseline_excluded_n", pa.uint64(), nullable=False),
            pa.field("baseline_missing_n", pa.uint64(), nullable=False),
            pa.field("baseline_out_of_domain_n", pa.uint64(), nullable=False),
            pa.field("candidate_attempted_n", pa.uint64(), nullable=False),
            pa.field("candidate_eligible_n", pa.uint64(), nullable=False),
            pa.field("candidate_failed_n", pa.uint64(), nullable=False),
            pa.field("candidate_excluded_n", pa.uint64(), nullable=False),
            pa.field("candidate_missing_n", pa.uint64(), nullable=False),
            pa.field("candidate_out_of_domain_n", pa.uint64(), nullable=False),
            pa.field("complete_pair_n", pa.uint64()),
            pa.field("multiplicity_json", pa.string()),
            pa.field("decision", pa.string(), nullable=False),
            pa.field("validity", pa.string(), nullable=False),
            pa.field("mismatches", pa.list_(pa.string()), nullable=False),
        ),
    ),
    "findings": _schema(
        "findings",
        (
            pa.field("finding_id", pa.string(), nullable=False),
            pa.field("revision", pa.int32(), nullable=False),
            pa.field("created_at", UTC_TIMESTAMP, nullable=False),
            pa.field("kind", pa.string(), nullable=False),
            pa.field("title", pa.string(), nullable=False),
            pa.field("claim", pa.string(), nullable=False),
            pa.field("evidence_level", pa.string(), nullable=False),
            pa.field("confidence", pa.string(), nullable=False),
            pa.field("assessment", pa.string(), nullable=False),
            pa.field("lifecycle", pa.string(), nullable=False),
            pa.field("limitations", pa.list_(pa.string()), nullable=False),
            pa.field("next_experiments_json", pa.string(), nullable=False),
        ),
    ),
    "otel_resources": _schema(
        "otel_resources",
        (
            pa.field("run_id", pa.string(), nullable=False),
            pa.field("artifact_id", pa.string(), nullable=False),
            pa.field("resource_ordinal", pa.uint64(), nullable=False),
            pa.field("schema_url", pa.string()),
            pa.field("attributes_json", pa.string(), nullable=False),
            pa.field("dropped_attributes_count", pa.uint64(), nullable=False),
        ),
    ),
    "otel_scopes": _schema(
        "otel_scopes",
        (
            pa.field("run_id", pa.string(), nullable=False),
            pa.field("artifact_id", pa.string(), nullable=False),
            pa.field("resource_ordinal", pa.uint64(), nullable=False),
            pa.field("scope_ordinal", pa.uint64(), nullable=False),
            pa.field("name", pa.string(), nullable=False),
            pa.field("version", pa.string()),
            pa.field("schema_url", pa.string()),
            pa.field("attributes_json", pa.string(), nullable=False),
            pa.field("dropped_attributes_count", pa.uint64(), nullable=False),
        ),
    ),
    "otel_spans": _schema(
        "otel_spans",
        (
            pa.field("run_id", pa.string(), nullable=False),
            pa.field("artifact_id", pa.string(), nullable=False),
            pa.field("resource_ordinal", pa.uint64(), nullable=False),
            pa.field("scope_ordinal", pa.uint64(), nullable=False),
            pa.field("source_ordinal", pa.uint64(), nullable=False),
            pa.field("trace_id", pa.string(), nullable=False),
            pa.field("span_id", pa.string(), nullable=False),
            pa.field("parent_span_id", pa.string()),
            pa.field("name", pa.string(), nullable=False),
            pa.field("kind", pa.int32(), nullable=False),
            pa.field("start_time_unix_nano", pa.uint64(), nullable=False),
            pa.field("end_time_unix_nano", pa.uint64(), nullable=False),
            pa.field("duration_ns", pa.int64()),
            pa.field("trace_state", pa.string(), nullable=False),
            pa.field("flags", pa.uint32(), nullable=False),
            pa.field("status_code", pa.int32(), nullable=False),
            pa.field("status_message", pa.string(), nullable=False),
            pa.field("attributes_json", pa.string(), nullable=False),
            pa.field("dropped_attributes_count", pa.uint64(), nullable=False),
            pa.field("dropped_events_count", pa.uint64(), nullable=False),
            pa.field("dropped_links_count", pa.uint64(), nullable=False),
        ),
    ),
    "otel_span_events": _schema(
        "otel_span_events",
        (
            pa.field("run_id", pa.string(), nullable=False),
            pa.field("artifact_id", pa.string(), nullable=False),
            pa.field("trace_id", pa.string(), nullable=False),
            pa.field("span_id", pa.string(), nullable=False),
            pa.field("source_ordinal", pa.uint64()),
            pa.field("event_ordinal", pa.uint64(), nullable=False),
            pa.field("time_unix_nano", pa.uint64(), nullable=False),
            pa.field("name", pa.string(), nullable=False),
            pa.field("attributes_json", pa.string(), nullable=False),
            pa.field("dropped_attributes_count", pa.uint64(), nullable=False),
        ),
    ),
    "otel_span_links": _schema(
        "otel_span_links",
        (
            pa.field("run_id", pa.string(), nullable=False),
            pa.field("artifact_id", pa.string(), nullable=False),
            pa.field("trace_id", pa.string(), nullable=False),
            pa.field("span_id", pa.string(), nullable=False),
            pa.field("source_ordinal", pa.uint64()),
            pa.field("link_ordinal", pa.uint64(), nullable=False),
            pa.field("linked_trace_id", pa.string(), nullable=False),
            pa.field("linked_span_id", pa.string(), nullable=False),
            pa.field("trace_state", pa.string(), nullable=False),
            pa.field("flags", pa.uint32(), nullable=False),
            pa.field("attributes_json", pa.string(), nullable=False),
            pa.field("dropped_attributes_count", pa.uint64(), nullable=False),
        ),
    ),
    "process_snapshots": _schema(
        "process_snapshots",
        (
            pa.field("run_id", pa.string(), nullable=False),
            pa.field("artifact_id", pa.string()),
            pa.field("snapshot_id", pa.string(), nullable=False),
            pa.field("phase", pa.string(), nullable=False),
            pa.field("observed_at", UTC_TIMESTAMP, nullable=False),
            pa.field("entry_count", pa.uint64(), nullable=False),
            pa.field("sources_json", pa.string(), nullable=False),
            pa.field("limitations", pa.list_(pa.string()), nullable=False),
        ),
    ),
    "process_snapshot_entries": _schema(
        "process_snapshot_entries",
        (
            pa.field("snapshot_id", pa.string(), nullable=False),
            pa.field("pid", pa.uint64(), nullable=False),
            pa.field("create_time", pa.float64()),
            pa.field("parent_pid", pa.uint64()),
            pa.field("parent_create_time", pa.float64()),
            pa.field("discovery_source", pa.string(), nullable=False),
            pa.field("name", pa.string()),
            pa.field("status", pa.string()),
            pa.field("rss_bytes", pa.uint64()),
            pa.field("cpu_user_seconds", pa.float64()),
            pa.field("cpu_system_seconds", pa.float64()),
            pa.field("thread_count", pa.uint64()),
            pa.field("fd_count", pa.uint64()),
            pa.field("observed_at", UTC_TIMESTAMP, nullable=False),
            pa.field("alive_before_cleanup", pa.bool_()),
            pa.field("cleanup_action", pa.string()),
            pa.field("cleanup_outcome", pa.string()),
            pa.field("failures_json", pa.string(), nullable=False),
        ),
    ),
}


def schema_for(table: str) -> pa.Schema:
    try:
        return SCHEMAS[table]
    except KeyError as exc:
        raise ValueError(f"Unknown evidence table: {table}") from exc


def table_names() -> tuple[str, ...]:
    return tuple(SCHEMAS)
