from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING

# The conditional imports below exist only for static type checkers; runtime
# exports are resolved lazily to keep short-lived transports lightweight.
# ruff: noqa: F405

if TYPE_CHECKING:
    from flameox.application.analysis_records import *  # noqa: F403
    from flameox.application.artifacts import *  # noqa: F403
    from flameox.application.capabilities import *  # noqa: F403
    from flameox.application.capture import *  # noqa: F403
    from flameox.application.compaction import *  # noqa: F403
    from flameox.application.comparisons import *  # noqa: F403
    from flameox.application.dependencies import *  # noqa: F403
    from flameox.application.detached import *  # noqa: F403
    from flameox.application.discovery import *  # noqa: F403
    from flameox.application.drilldown import *  # noqa: F403
    from flameox.application.evidence_lookup import *  # noqa: F403
    from flameox.application.evidence_query import *  # noqa: F403
    from flameox.application.execution_identity import *  # noqa: F403
    from flameox.application.execution_policy import *  # noqa: F403
    from flameox.application.experiments import *  # noqa: F403
    from flameox.application.faults import *  # noqa: F403
    from flameox.application.gc import *  # noqa: F403
    from flameox.application.imports import *  # noqa: F403
    from flameox.application.inference import *  # noqa: F403
    from flameox.application.inference_profiling import *  # noqa: F403
    from flameox.application.inference_providers import *  # noqa: F403
    from flameox.application.integrity import *  # noqa: F403
    from flameox.application.kernel_builds import *  # noqa: F403
    from flameox.application.kernel_validation_comparisons import *  # noqa: F403
    from flameox.application.lifecycle import *  # noqa: F403
    from flameox.application.nvbench_imports import *  # noqa: F403
    from flameox.application.operations import *  # noqa: F403
    from flameox.application.otlp import *  # noqa: F403
    from flameox.application.pipelines import *  # noqa: F403
    from flameox.application.preflight import *  # noqa: F403
    from flameox.application.projections import *  # noqa: F403
    from flameox.application.quarantine import *  # noqa: F403
    from flameox.application.records import *  # noqa: F403
    from flameox.application.recovery import *  # noqa: F403
    from flameox.application.reduction_contracts import *  # noqa: F403
    from flameox.application.reductions import *  # noqa: F403
    from flameox.application.run_projection import *  # noqa: F403
    from flameox.application.setup import *  # noqa: F403
    from flameox.application.status import *  # noqa: F403
    from flameox.application.summaries import *  # noqa: F403
    from flameox.application.viewers import *  # noqa: F403
    from flameox.application.workloads import *  # noqa: F403
    from flameox.application.xctrace import *  # noqa: F403

_MODULES = (
    "analysis_records",
    "artifacts",
    "capabilities",
    "capture",
    "compaction",
    "comparisons",
    "dependencies",
    "detached",
    "discovery",
    "drilldown",
    "evidence_lookup",
    "evidence_query",
    "execution_identity",
    "execution_policy",
    "experiments",
    "faults",
    "gc",
    "imports",
    "inference",
    "inference_profiling",
    "lifecycle",
    "reduction_contracts",
    "otlp",
    "integrity",
    "kernel_builds",
    "kernel_validation_comparisons",
    "inference_providers",
    "nvbench_imports",
    "operations",
    "pipelines",
    "preflight",
    "projections",
    "quarantine",
    "records",
    "recovery",
    "reductions",
    "run_projection",
    "setup",
    "status",
    "summaries",
    "viewers",
    "workloads",
    "xctrace",
)


__all__ = [
    "AIPerfProfileRequest",
    "AIPerfReplayPlan",
    "AcceleratorLaunchAnalysisRequest",
    "AdapterOption",
    "AdapterPreparationResult",
    "AddedPipelineStageComparison",
    "AgentRunProjection",
    "AgentRunProjectionStatus",
    "AnalysisMaterializationService",
    "ArtifactListItem",
    "ArtifactListResult",
    "ArtifactMetadataResult",
    "ArtifactPipeline",
    "ArtifactPipelineService",
    "ArtifactRegistrationSummary",
    "ArtifactService",
    "AvailableInferenceToolDiscovery",
    "BandwidthFault",
    "CallEdgeResult",
    "CapabilityList",
    "CapabilityService",
    "CapabilitySetupManager",
    "CapabilitySetupResult",
    "CapturePlanRegistry",
    "CaptureResult",
    "CaptureService",
    "ClientSetupPlan",
    "CompactionResult",
    "CompactionService",
    "CompareRunSetsRequest",
    "ComparisonResult",
    "ComparisonService",
    "ConfigurationAction",
    "ConfigurationOperation",
    "ConfigureInferenceScenarioRequest",
    "ConfigureInferenceServerRequest",
    "ConfigureWorkloadRequest",
    "CreateInvestigationRequest",
    "DeclaredWorkflowDetail",
    "DeclaredWorkflowKind",
    "DeclaredWorkflowList",
    "DeclaredWorkflowRequirement",
    "DeclaredWorkflowSummary",
    "DetachedCaptureManager",
    "DetachedCaptureRecord",
    "DetachedCaptureStatus",
    "DetachedProgress",
    "DiscoveryCoverage",
    "DrilldownService",
    "EvidenceInput",
    "EvidenceLookupResult",
    "EvidenceLookupService",
    "EvidenceQueryService",
    "EvidenceSummary",
    "EvidenceSummaryBundle",
    "EvidenceSummaryRequest",
    "EvidenceSummaryService",
    "ExcludedFreezeRunSetMember",
    "ExecutionAnalysisRequest",
    "ExecutionIdentityService",
    "ExecutionPolicy",
    "ExistingServerProbe",
    "ExperimentBlock",
    "ExperimentCell",
    "ExperimentConfig",
    "ExperimentPlan",
    "ExperimentPlanRegistry",
    "ExperimentRunResult",
    "ExperimentService",
    "ExperimentTrialCollection",
    "FailureAnalysisRequest",
    "FaultExperimentConfig",
    "FaultExperimentPlan",
    "FaultExperimentResult",
    "FaultExperimentService",
    "FindingListResult",
    "FindingResult",
    "FindingService",
    "FrameDetail",
    "FreezeRunIdsRequest",
    "FreezeRunMembersRequest",
    "FreezeRunSetMember",
    "FreezeRunSetRequest",
    "GarbageApplyResult",
    "GarbageCollector",
    "GarbageEntry",
    "GarbagePlan",
    "GarbagePurgeResult",
    "GarbageRestoreResult",
    "HotspotAnalysisRequest",
    "ImportArtifactRequest",
    "ImportResult",
    "ImportService",
    "IncludedFreezeRunSetMember",
    "InferenceConfigurationKind",
    "InferenceConfigurationList",
    "InferenceConfigurationResult",
    "InferenceEndpointType",
    "InferenceProfileCoverage",
    "InferenceProfilingPlan",
    "InferenceProfilingResult",
    "InferenceProfilingService",
    "InferenceReplayPlan",
    "InferenceReplayResult",
    "InferenceReplayService",
    "InferenceRequestItem",
    "InferenceRequestQueryResult",
    "InferenceScenarioConfig",
    "InferenceScenarioProvider",
    "InferenceServerConfig",
    "InferenceServerMode",
    "InferenceServerProvider",
    "InferenceTool",
    "InferenceToolDiscovery",
    "IntegrityIssue",
    "IntegrityLevel",
    "IntegrityResult",
    "IntegrityService",
    "IntegritySeverity",
    "InvestigationListResult",
    "InvestigationService",
    "KernelBuildCaptureCollector",
    "KernelBuildImportResult",
    "KernelBuildImportService",
    "KernelMetricChangeKind",
    "KernelMetricDirection",
    "KernelValidationCompareRequest",
    "KernelValidationComparison",
    "KernelValidationComparisonProtocol",
    "KernelValidationComparisonResult",
    "KernelValidationComparisonService",
    "KernelValidationCompatibilityMismatch",
    "KernelValidationInputIdentity",
    "KernelValidationMetricAggregate",
    "KernelValidationMetricPair",
    "KernelValidationMetricSelector",
    "KernelValidationPsnrProfile",
    "KernelValidationUnmatchedMetric",
    "LatencyFault",
    "LifecycleEvidenceService",
    "LifecycleItem",
    "LifecycleQueryResult",
    "LimitDataFault",
    "MaterializeAnalysisRequest",
    "MaterializedAnalysisResult",
    "MeasurementCompareRunSetsRequest",
    "MeasurementItem",
    "MeasurementQueryResult",
    "MemoryAnalysisRequest",
    "MissingPipelineStageComparison",
    "NativeViewerLaunchResult",
    "NativeViewerPlan",
    "NativeViewerService",
    "NsightSystemsProfilingPlan",
    "NvbenchImportResult",
    "NvbenchImportService",
    "OperationFailure",
    "OperationItemOutcome",
    "OperationProgress",
    "OperationRecord",
    "OperationRecovery",
    "OperationRunner",
    "OperationState",
    "OperationStatus",
    "OtlpExtractionResult",
    "OtlpTraceService",
    "OutcomeCount",
    "OutcomeExperimentResult",
    "PairedPipelineStageComparison",
    "PipelineComparison",
    "PipelineCompatibility",
    "PipelineExtractorProfile",
    "PipelineIdentityQuality",
    "PipelineStage",
    "PipelineStageComparison",
    "PipelineStageDeclaration",
    "PipelineStageDisposition",
    "PipelineStageStatus",
    "PlanReductionRequest",
    "PredicateClassification",
    "PredicateObservation",
    "PreflightService",
    "ProfileChange",
    "ProjectConfig",
    "ProjectionCoordinator",
    "ProjectionReconciliationResult",
    "ProjectionVisibilityState",
    "ProxyFault",
    "PublishedRunProjection",
    "PyTorchAnalysisRequest",
    "QuarantineManifest",
    "QuarantineRestoreResult",
    "QuarantineService",
    "RecordFindingRequest",
    "RecordHypothesisRequest",
    "RecoveryInspection",
    "RecoveryResult",
    "RecoveryService",
    "ReductionAttemptReceipt",
    "ReductionAttemptSummary",
    "ReductionDisposition",
    "ReductionExecutionLimits",
    "ReductionFormat",
    "ReductionLimits",
    "ReductionMinimality",
    "ReductionPlan",
    "ReductionRepeatabilityStatus",
    "ReductionResult",
    "ReductionService",
    "RegisterPipelineRequest",
    "RegisteredPipelineStage",
    "RegisteredPipelineStageDeclaration",
    "ResetPeerFault",
    "ResolvedOracle",
    "ResolvedSetupPlan",
    "RunDiscoveryService",
    "RunFilter",
    "RunListResult",
    "RunProjectionService",
    "RunSetService",
    "RunSummary",
    "RuntimeAction",
    "RuntimeResourceCompareRunSetsRequest",
    "Scalar",
    "ScalingAnalysisRequest",
    "SetupInspection",
    "SetupOperation",
    "SetupPlan",
    "SetupReport",
    "SetupService",
    "SetupVerification",
    "SglangBenchReplayPlan",
    "SglangTorchProfilingPlan",
    "SlicerFault",
    "SlowCloseFault",
    "StackExample",
    "StackExamplesResult",
    "SummaryArtifact",
    "SummaryClaim",
    "SummaryClaimedRole",
    "SummaryExcerptPolicy",
    "SummaryProofAssessment",
    "SummaryProofShape",
    "SummaryReference",
    "SummaryReferenceKind",
    "SummaryRun",
    "SummaryRunRole",
    "SummarySelectionShape",
    "SummarySensitiveContextPolicy",
    "SummarySupportStatus",
    "SupportedInferenceProfiler",
    "TimeoutFault",
    "TrashManifest",
    "UnavailableInferenceToolDiscovery",
    "UnregisteredPipelineStage",
    "UnregisteredPipelineStageDeclaration",
    "VllmBenchReplayPlan",
    "VllmBenchServeRequest",
    "VllmProfilerControlClient",
    "VllmTorchProfilingPlan",
    "WorkloadConfig",
    "WorkloadConfigurationResult",
    "WorkloadConfigurationStatus",
    "WorkloadDependencyService",
    "WorkloadDependencySetupResult",
    "WorkloadIdentityConfig",
    "WorkloadInspection",
    "WorkloadOracleConfig",
    "WorkloadRequirementsConfig",
    "WorkloadService",
    "WorkspaceStatus",
    "XctraceCapability",
    "XctraceImportRequest",
    "XctraceImportResult",
    "XctraceService",
    "discover_inference_tool",
    "kernel_build_pipeline_request",
    "managed_kernel_build_context",
    "parse_compare_run_sets_request",
    "parse_experiment_config",
    "parse_inference_profiling_plan",
    "parse_inference_replay_plan",
    "parse_inference_scenario_config",
    "parse_inference_server_config",
    "parse_inference_tool_discovery",
    "probe_existing_vllm_server",
    "probe_existing_vllm_server_async",
    "render_evidence_summary_markdown",
    "safe_run_semantics",
    "scalar_contains",
    "scalar_equal",
    "scalar_identity",
    "scalar_identity_set",
    "scalar_subset",
    "workspace_status",
]


def __getattr__(name: str) -> object:
    if name not in __all__:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    for module_name in _MODULES:
        module = import_module(f"{__name__}.{module_name}")
        try:
            value = getattr(module, name)
        except AttributeError:
            continue
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
